model:
  type: AttentionUNet
  in_channels: [100, 400]
  out_channels: 5
  filters_options:
    - [16, 32, 64]
    - [16, 32, 64, 128]
    - [16, 32, 64, 128, 256]
    - [32, 64, 128, 256, 512]
  kernel_size_options:
    - [3, 3, 3]
    - [3, 3, 3, 3]
    - [3, 3, 3, 3, 3]
    - [3, 3, 3, 3, 3, 3]
  att_channels_options: [16, 32, 64]
  # activation_options: [relu] #, leaky_relu, gelu]

training:
  epochs: 30
  batch_sizes: [16, 32, 64, 128]
  learning_rates: [0.00001, 0.00005,  0.0001, 0.001]
  loss_functions: [dice_loss_multi_class, focal_loss] #focal_loss, MSELoss, L1Loss]
  n_trials: 48
  gpu_ids: [0,1,2,3]
  use_parallel: True
  n_jobs: 4

data:
  train_path: /scratch/phys/sin/sethih1/data_files/all_group_plane_fchk_split_images_ters/train
  val_path: /scratch/phys/sin/sethih1/data_files/all_group_plane_fchk_split_images_ters/val
  split_by_id: 0
  circle_radius: 5
  augmentation: [True, False]

save_path: /scratch/phys/sin/sethih1/models/all_group_plane_fchk_split_images_ters/composnet_hyperopt_all_multi_class/config_hypopt_all/
log_path: /scratch/phys/sin/sethih1/runs_ters/all_group_plane_fchk_split_images_ters/composnet_hyperopt_all_multi_class/config_hypopt_all/
